# Generated by Django 4.0.4 on 2022-05-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_db_search', '0001_initial'),
    ]

    operations = [
    ]
