# Generated by Django 4.0.4 on 2022-05-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_etl_delete_segment_delete_tablerefer'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_data_caltalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, null=True)),
                ('source_type', models.CharField(max_length=100, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('destination_type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
